baseURL = "https://til.chriswheeler.dev/"
title = "Chris' TILs"
languageCode = "en-us"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true  # for syntax highlighting
pygmentsUseClasses = true  # for syntax highlighting

[params]
  description = "A bunch of posts about what I learned"
  copyright = "Copyright © 2020-2025 Chris Wheeler"
  dark = "auto"
  highlight = true  # for syntax highlighting

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:filename/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
